/* =====================================================================
   FACE-OFF: CYSA+  —  ACRONYM POOL
   Exam: CompTIA CySA+ CS0-003
   ---------------------------------------------------------------------
   GENERATED FILE — do not hand-edit.
   Rebuild with:  python3 tools/build-acronyms.py
   Source of truth: the CYSA+ acronym repo's data/acronyms.json.

   175 acronyms in 13 categories.

   THERE IS NO DIFFICULTY RAMP IN AN ACRONYM. Nothing makes MAC a 100
   and SD-WAN a 500, which is a problem on a board whose whole shape is
   a column climbing 100 to 500. So the ramp is the TASK, not the item:
   the cheap rows ask you to expand the letters, the middle rows give
   you a description and ask which acronym it is, and the dear rows
   give you the acronym and ask what it actually does. Same acronym,
   three difficulties — which is also why 175 acronyms go a long way.

   The clue text is built at draw time from these three fields, so
   there is no answer bank to memorise and editing an acronym here
   changes every form of it at once.

     ac = the acronym          ex = what the letters stand for
     df = what it actually does
     amb = set only when this acronym means something else somewhere
           in the bank; the clue names this field so the team is not
           marked wrong for giving the other correct expansion.
   ===================================================================== */

window.FACEOFF_ACRONYMS = {
  categories: [
    { name: "NETWORK PROTOCOLS",
      items: [
      { ac: "ARP",
        ex: "Address Resolution Protocol",
        df: "A protocol used to map IP addresses to physical MAC addresses in a local network." },
      { ac: "BGP",
        ex: "Border Gateway Protocol",
        df: "A routing protocol used to exchange routing information between autonomous systems on the internet." },
      { ac: "DHCP",
        ex: "Dynamic Host Configuration Protocol",
        df: "Protocol that automatically assigns IP addresses and network settings to devices on a network" },
      { ac: "DNS",
        ex: "Domain Name System",
        df: "A naming system that translates human-readable domain names into IP addresses computers use to identify each other." },
      { ac: "DoH",
        ex: "DNS over HTTPS",
        df: "A method of sending DNS queries over HTTPS to improve privacy and reduce tampering." },
      { ac: "FTP",
        ex: "File Transfer Protocol",
        df: "Standard for transferring files between systems." },
      { ac: "ICMP",
        ex: "Internet Control Message Protocol",
        df: "A network protocol used for sending error messages and operational information about IP traffic." },
      { ac: "IP",
        ex: "Internet Protocol",
        df: "The primary protocol for sending data across networks assigning addresses and routing packets." },
      { ac: "LAN",
        ex: "Local Area Network",
        df: "Network covering a small, local area (e.g., office)." },
      { ac: "MAC",
        ex: "Media Access Control",
        df: "A unique hardware identifier assigned to network interfaces for communications on the physical network." },
      { ac: "NTP",
        ex: "Network Time Protocol",
        df: "A protocol used to synchronize clocks between systems over a network critical for accurate logging and security." },
      { ac: "OUI",
        ex: "Organizationally Unique Identifier",
        df: "A manufacturer identifier used in the first part of a MAC address to identify the vendor." },
      { ac: "RDP",
        ex: "Remote Desktop Protocol",
        df: "A Microsoft protocol that allows users to remotely access and control a Windows computer." },
      { ac: "SFTP",
        ex: "Secured File Transfer Protocol",
        df: "A secure version of FTP that uses SSH to encrypt file transfers and protect data in transit." },
      { ac: "SMB",
        ex: "Server Message Block",
        df: "Network protocol for sharing files printers and serial ports between nodes on a network" },
      { ac: "SMTP",
        ex: "Simple Mail Transfer Protocol",
        df: "Protocol used to send email from clients to servers and between servers" },
      { ac: "SNI",
        ex: "SMS Notification Indicator",
        df: "Protocol used for exchanging structured information in web services using XML" },
      { ac: "SNMP",
        ex: "Simple Network Management Protocol",
        df: "Protocol used to monitor and manage devices on a network such as routers and switches" },
      { ac: "SSH",
        ex: "Secure Shell",
        df: "Protocol that provides secure remote command-line access and encrypted data communication" },
      { ac: "TCP",
        ex: "Transmission Control Protocol",
        df: "Communication protocols that governs how data is transmitted across networks." },
      { ac: "TFTP",
        ex: "Trivial File Transfer Protocol",
        df: "Simple, lightweight file transfer system." },
      { ac: "UDP",
        ex: "User Datagram Protocol",
        df: "Connectionless communication protocol used for fast data transmission but with no error correction" },
      { ac: "URI",
        ex: "Uniform Resource Identifier",
        df: "A general identifier used to locate or identify resources on the internet including URLs and URNs." },
      { ac: "URL",
        ex: "Universal Resource Locator",
        df: "A specific type of URI that provides the address to access resources on the internet (e.g. https://example.com)." },
      { ac: "UTC",
        ex: "Universal Time Coordinated",
        df: "The primary global time standard used for consistent timekeeping and synchronization." },
      { ac: "VLAN",
        ex: "Virtual Local Area Network",
        df: "A logical grouping of devices on a network segmented by function or department improving security." },
      { ac: "WAN",
        ex: "Wide Area Network",
        df: "Network spanning a large geographic area." },
      ] },
    { name: "GOVERNANCE & FRAMEWORKS",
      items: [
      { ac: "CHD",
        ex: "Cardholder Data",
        df: "Information tied to credit/debit cardholders." },
      { ac: "CIS",
        ex: "Center for Internet Security",
        df: "Creates cybersecurity benchmarks and best practices." },
      { ac: "COBIT",
        ex: "Control Objectives for Information and Related Technologies",
        df: "Framework for IT governance and management." },
      { ac: "CSF",
        ex: "Cybersecurity Framework",
        df: "A set of best-practice guidelines for managing cybersecurity risk (commonly referring to the NIST Cybersecurity Framework)." },
      { ac: "DLP",
        ex: "Data Loss Prevention",
        df: "Tools and strategies used to prevent unauthorized access transmission or leakage of sensitive information." },
      { ac: "ISO",
        ex: "International Standards Organization",
        df: "An international body that creates standards for technology including information security (e.g. ISO/IEC 27001)." },
      { ac: "IT",
        ex: "Information Technology",
        df: "Use of computers, networks, and systems for data." },
      { ac: "ITIL",
        ex: "Information Technology Infrastructure Library",
        df: "Framework for IT service management best practices." },
      { ac: "KPI",
        ex: "Key Performance Indicator",
        df: "Metric to measure progress toward goals." },
      { ac: "LOI",
        ex: "Letter of Intent",
        df: "Preliminary agreement document." },
      { ac: "MOU",
        ex: "Memorandum of Understanding",
        df: "A non-binding agreement that outlines terms and expectations for collaboration between entities." },
      { ac: "NDA",
        ex: "Non-disclosure Agreement",
        df: "Contract protecting confidential information." },
      { ac: "NIST",
        ex: "National Institute of Standards & Technology",
        df: "US agency that develops cybersecurity standards and guidelines including the NIST Cybersecurity Framework" },
      { ac: "PCI DSS",
        ex: "Payment Card Industry Data Security Standard",
        df: "A set of standards ensuring secure handling of credit card information." },
      { ac: "PII",
        ex: "Personally Identifiable Information",
        df: "Any data that can identify a person such as name SSN or email critical for data privacy." },
      { ac: "SLA",
        ex: "Service-level Agreement",
        df: "A contract between a service provider and customer that outlines performance availability and responsibilities" },
      { ac: "SLO",
        ex: "Service-level Objective",
        df: "Performance or reliability target for a service." },
      ] },
    { name: "APPLICATION & DEVELOPMENT",
      items: [
      { ac: "API",
        ex: "Application Programming Interface",
        df: "A set of protocols allowing different software applications to communicate securely." },
      { ac: "CI/CD",
        ex: "Continuous Integration and Continuous Delivery",
        df: "Automating code build, testing, and deployment." },
      { ac: "CMS",
        ex: "Content Management System",
        df: "Software used to create, manage, and publish website content." },
      { ac: "DLL",
        ex: "Dynamic Link Library",
        df: "Shared library of code used by multiple programs in Windows allowing modular and efficient software functionality" },
      { ac: "HTML",
        ex: "Hypertext Markup Language",
        df: "Standard language used to create and format content for web pages" },
      { ac: "HTTPD",
        ex: "Hypertext Transfer Protocol Daemon",
        df: "A web server daemon (service) that handles HTTP requests and serves web pages." },
      { ac: "IIS",
        ex: "Internet Information Services",
        df: "Microsoft's web server platform used to host websites and web applications." },
      { ac: "JSON",
        ex: "JavaScript Object Notation",
        df: "Lightweight data exchange format." },
      { ac: "MSRPC",
        ex: "Microsoft Remote Procedure Call",
        df: "Microsoft's implementation of Remote Procedure Call used for inter-process and network-based service requests." },
      { ac: "PHP",
        ex: "Hypertext Preprocessor",
        df: "Widely used server-side scripting language." },
      { ac: "REST",
        ex: "Representational State Transfer",
        df: "Web service design style using standard HTTP." },
      { ac: "RPC",
        ex: "Remote Procedure Call",
        df: "A protocol that lets a program request a service or execute a function on another system remotely." },
      { ac: "SDLC",
        ex: "Software Development Lifecycle",
        df: "A structured process for planning developing testing and deploying software systems." },
      { ac: "SOAP",
        ex: "Simple Object Access Protocol",
        df: "A protocol for exchanging structured messages between systems, often using XML over HTTP." },
      { ac: "SQL",
        ex: "Structured Query Language",
        df: "A standard language used for managing and querying databases." },
      { ac: "XML",
        ex: "Extensible Markup Language",
        df: "A flexible format for storing and transporting structured data often used in web and security applications" },
      ] },
    { name: "DETECTION & MONITORING",
      items: [
      { ac: "AV",
        ex: "Antivirus",
        df: "Software that detects prevents and removes malicious software from systems." },
      { ac: "EDR",
        ex: "Endpoint Detection and Response",
        df: "A security solution that monitors endpoints for malicious activity and provides real-time threat response." },
      { ac: "FIM",
        ex: "File Integrity Management",
        df: "A process that monitors and detects changes to files helping identify unauthorized modifications or corruption." },
      { ac: "HIDS",
        ex: "Host-based Intrusion Detection System",
        df: "Software that monitors a single system for suspicious activity or policy violations." },
      { ac: "HIPS",
        ex: "Host-based Intrusion Prevention System",
        df: "Software that detects and actively blocks malicious behavior on an individual host." },
      { ac: "IDS",
        ex: "Intrusion Detection System",
        df: "A system that monitors network or system activity for signs of security breaches or malicious behavior." },
      { ac: "IPS",
        ex: "Intrusion Prevention System",
        df: "A system that actively monitors and blocks detected threats or unauthorized activity in real- time." },
      { ac: "MTTD",
        ex: "Mean Time to Detect",
        df: "Average time to discover a security incident." },
      { ac: "NIDS",
        ex: "Network-based Intrusion Detection System",
        df: "A system that monitors network traffic for signs of malicious activity or policy violations." },
      { ac: "NIPS",
        ex: "Network-based Intrusion Prevention System",
        df: "Security system that inspects network traffic and blocks threats in real time" },
      { ac: "NOC",
        ex: "Network Operations Center",
        df: "A centralized team/location that monitors networks and systems to keep services available and stable." },
      { ac: "SIEM",
        ex: "Security Information and Event Management",
        df: "A centralized solution for collecting analyzing and correlating security data in real time." },
      { ac: "SOAR",
        ex: "Security Orchestration Automation Response",
        df: "A platform that integrates security tools to automate and streamline incident response." },
      { ac: "SOC",
        ex: "Security Operations Center",
        df: "A centralized team and facility that monitors and manages an organization's security posture." },
      { ac: "UEBA",
        ex: "User and Entity Behavior Analytics",
        df: "Security using behavior patterns to detect threats." },
      { ac: "XDR",
        ex: "Extended Detection and Response",
        df: "A cybersecurity approach that integrates threat data across endpoints networks and servers for holistic response." },
      ] },
    { name: "WEB & APPLICATION ATTACKS",
      items: [
      { ac: "BEAST",
        ex: "Browser Exploit Against SSL/TLS",
        df: "An attack that exploits weaknesses in older TLS/SSL encryption to help recover sensitive data." },
      { ac: "BREACH",
        ex: "Browser Reconnaissance & Exfiltration via Adaptive Compression of Hypertext",
        df: "A web attack that uses HTTP compression to extract secret data from encrypted HTTPS responses." },
      { ac: "CSRF",
        ex: "Cross-site Request Forgery",
        df: "A web attack where users are tricked into performing actions they didn't intend while authenticated." },
      { ac: "DDoS",
        ex: "Distributed Denial of Service",
        df: "A type of attack that overwhelms a service with traffic from multiple sources causing disruption or shutdown." },
      { ac: "DoS",
        ex: "Denial of Service",
        df: "Attack that aims to shut down a service or system by flooding it with traffic or triggering resource exhaustion" },
      { ac: "IDOR",
        ex: "Insecure Direct Object Reference",
        df: "Critical access control vulnerability occurring when an application uses user-supplied input to directly access internal objects (e.g., database keys, files) without proper authorization checks. Attackers exploit this by manipulating IDs in URLs or parameters to access or modify unauthorized data" },
      { ac: "LFI",
        ex: "Local File Inclusion",
        df: "Vulnerability allowing execution of local files." },
      { ac: "RCE",
        ex: "Remote Code Execution",
        df: "Vulnerability enabling remote attacker code execution." },
      { ac: "RFI",
        ex: "Remote File Inclusion",
        df: "Vulnerability letting attackers load remote files." },
      { ac: "RXSS",
        ex: "Reflected Cross-site Scripting",
        df: "Injection attack bouncing malicious code to a user." },
      { ac: "SQLi",
        ex: "SQL Injection",
        df: "Type of attack where malicious SQL code is inserted into input fields to access or manipulate a database" },
      { ac: "SSRF",
        ex: "Server-side Request Forgery",
        df: "Attack tricking a server into making requests." },
      { ac: "TRACE",
        ex: "Trade Reporting and Compliance Engine",
        df: "FINRA system for reporting bond trades." },
      { ac: "XSS",
        ex: "Cross-site Scripting",
        df: "A web vulnerability where attackers inject malicious scripts into websites viewed by other users." },
      { ac: "XXE",
        ex: "XML External Entity",
        df: "XML parsing flaw that can expose or alter data." },
      ] },
    { name: "INCIDENT RESPONSE & FORENSICS",
      items: [
      { ac: "BC",
        ex: "Business Continuity",
        df: "Ability to keep critical operations running during/after disruptions." },
      { ac: "BCP",
        ex: "Business Continuity Planning",
        df: "The process of creating systems to recover operations during and after a crisis." },
      { ac: "BIA",
        ex: "Business Impact Analysis",
        df: "A process to predict and evaluate the impact of disruption to business functions." },
      { ac: "CERT",
        ex: "Computer Emergency Response Team",
        df: "A group that responds to cybersecurity incidents and helps mitigate their effects." },
      { ac: "CSIRT",
        ex: "Cybersecurity Incident Response Team",
        df: "Handles and responds to security incidents." },
      { ac: "DR",
        ex: "Disaster Recovery",
        df: "Restoring IT systems and data after disruptions." },
      { ac: "EOF",
        ex: "End Of File",
        df: "A marker that indicates no more data can be read from a file or data stream." },
      { ac: "FTK",
        ex: "Forensic Toolkit",
        df: "A digital forensics tool used to acquire, analyze, and report on evidence from computers and storage media." },
      { ac: "GDB",
        ex: "GNU Debugger",
        df: "Tool for analyzing and debugging program behavior." },
      { ac: "IR",
        ex: "Incident Response",
        df: "The process of detecting analyzing and responding to security incidents to minimize damage." },
      { ac: "LSASS",
        ex: "Local Security Authority Subsystem Service",
        df: "A Windows process that enforces security policy and handles user authentication and token creation." },
      { ac: "PID",
        ex: "Process Identifier",
        df: "Unique number assigned to a running process." },
      { ac: "RPO",
        ex: "Recovery Point Objective",
        df: "Maximum acceptable amount of data loss measured in time used in disaster recovery planning" },
      { ac: "RTO",
        ex: "Recovery Time Objective",
        df: "Target time to restore systems and operations, including data, after a disruption or disaster." },
      ] },
    { name: "ENCRYPTION & CERTIFICATES",
      items: [
      { ac: "CA",
        ex: "Certificate Authority",
        df: "A trusted organization that issues digital certificates to verify identity and enable secure communications." },
      { ac: "CBC",
        ex: "Cipher Block Chain",
        df: "A block-cipher mode where each plaintext block is combined with the previous ciphertext block before encryption." },
      { ac: "DKIM",
        ex: "DomainKeys Identified Mail",
        df: "An email authentication method that verifies a sender's domain using a digital signature to prevent spoofing." },
      { ac: "DMARC",
        ex: "Domain Message Authentication Reporting and Conformance",
        df: "An email validation system that uses SPF and DKIM to prevent phishing and provides reporting." },
      { ac: "GPG",
        ex: "GNU Privacy Guard",
        df: "An encryption/signing tool used to protect data and verify authenticity using public-key cryptography." },
      { ac: "HTTP",
        ex: "Hypertext Transfer Protocol",
        df: "A protocol used to request and transfer web pages over the internet typically on port 80." },
      { ac: "HTTPS",
        ex: "Hypertext Transfer Protocol Secure",
        df: "The encrypted version of HTTP using TLS/SSL to secure web communications." },
      { ac: "LDAPS",
        ex: "Lightweight Directory Access Protocol",
        df: "A protocol used to access and maintain directory information like usernames and credentials." },
      { ac: "MD5",
        ex: "Message Digest 5",
        df: "Cryptographic hash function used for checksums now considered insecure due to vulnerability to collisions" },
      { ac: "PKI",
        ex: "Public Key Infrastructure",
        df: "A framework for managing digital certificates and public-key encryption to support secure communications." },
      { ac: "RSA",
        ex: "Rivest Shamir & Adleman",
        df: "Widely used asymmetric encryption algorithm known for secure data transmission." },
      { ac: "SPF",
        ex: "Sender Policy Framework",
        df: "An email validation system designed to prevent spoofing by verifying sender IPs." },
      { ac: "SSL",
        ex: "Secure Sockets Layer",
        df: "An older encryption protocol used to secure web communications now deprecated in favor of TLS." },
      { ac: "TLS",
        ex: "Transport Layer Security",
        df: "A cryptographic protocol that ensures privacy and data integrity between applications over a network." },
      ] },
    { name: "IDENTITY & ACCESS",
      items: [
      { ac: "ACL",
        ex: "Access Control List",
        df: "A set of rules attached to resources specifying who can access what and what actions are allowed." },
      { ac: "GPO",
        ex: "Group Policy Object",
        df: "A collection of settings in Windows used to control user and computer configurations in an Active Directory environment." },
      { ac: "IAM",
        ex: "Identity and Access Management",
        df: "Framework for ensuring the right individuals access the right resources at the right times" },
      { ac: "MFA",
        ex: "Multifactor Authentication",
        df: "A security method that requires two or more types of credentials for user authentication." },
      { ac: "NAC",
        ex: "Network Access Control",
        df: "A security solution that enforces policies for device compliance before allowing network access." },
      { ac: "PAM",
        ex: "Privileged Access Management",
        df: "Tools and strategies used to monitor and control accounts with elevated access rights to reduce risk." },
      { ac: "RADIUS",
        ex: "Remote Authentication Dial-in User Service",
        df: "Centralized protocol for authentication authorization and accounting in remote access" },
      { ac: "SAML",
        ex: "Security Assertions Markup Language",
        df: "An XML-based standard used for exchanging authentication and authorization data between parties." },
      { ac: "SSO",
        ex: "Single Sign-on",
        df: "A user authentication process that allows access to multiple systems with one set of credentials." },
      { ac: "ZTA",
        ex: "Zero Trust Architecture",
        df: "Security approach assumes no implicit trust and requires verification for every access request." },
      { ac: "ZTNA",
        ex: "Zero Trust Network Access",
        df: "Security model requiring verification for every connection." },
      ] },
    { name: "THREAT INTELLIGENCE",
      items: [
      { ac: "APT",
        ex: "Advanced Persistent Threat",
        df: "A prolonged targeted cyberattack in which attackers remain undetected for a long period." },
      { ac: "ATT&CK",
        ex: "Adversarial Tactics Techniques and Common Knowledge",
        df: "MITRE framework for understanding attacker behaviors and methods" },
      { ac: "C2",
        ex: "Command and Control",
        df: "Attacker system used to manage compromised devices." },
      { ac: "CVE",
        ex: "Common Vulnerability Enumeration",
        df: "A standardized identifier for known security vulnerabilities." },
      { ac: "CVSS",
        ex: "Common Vulnerability Scoring System",
        df: "A numerical scoring system to rate the severity of software vulnerabilities." },
      { ac: "IoC",
        ex: "Indicators of Compromise",
        df: "Evidence or artifacts that suggest a system has been breached or is under attack." },
      { ac: "OSINT",
        ex: "Open-source Intelligence",
        df: "Publicly available information (like websites or social media) used for investigative or threat intelligence purposes" },
      { ac: "OSVDB",
        ex: "Open-Source Vulnerability DB",
        df: "A database that catalogs publicly disclosed software vulnerabilities (historically community- driven)." },
      { ac: "POC",
        ex: "Proof of Concept",
        df: "Demo showing feasibility of an idea or exploit." },
      { ac: "STIX",
        ex: "Structured Threat Information eXchange",
        df: "A standardized format for sharing threat intelligence across organizations." },
      { ac: "TTP",
        ex: "Tactics Techniques and Procedures",
        df: "A cybersecurity framework describing how attackers operate and organize their behavior." },
      ] },
    { name: "VULNERABILITY MANAGEMENT",
      items: [
      { ac: "ASVS",
        ex: "Application Security Verification Standard",
        df: "A framework for testing and validating the security of web applications." },
      { ac: "DAST",
        ex: "Dynamic Application Security Testing",
        df: "Security testing that scans a running application from the outside to find vulnerabilities." },
      { ac: "DEP",
        ex: "Data Execution Prevention",
        df: "Security feature that blocks code from running in memory regions not designated for execution helping prevent exploits" },
      { ac: "MSF",
        ex: "Metasploit Framework",
        df: "Security tool for penetration testing and exploitation." },
      { ac: "OpenVAS",
        ex: "Open Vulnerability Assessment Scanner",
        df: "Standard for security testing." },
      { ac: "OSSTMM",
        ex: "Open-Source Security Testing Methodology Manual",
        df: "Standard for security testing." },
      { ac: "OWASP",
        ex: "Open Web Application Security Project",
        df: "Web app security nonprofit and resources." },
      { ac: "SAMM",
        ex: "Software Assurance Maturity Model",
        df: "A maturity model used to assess and improve an organization's software security practices." },
      { ac: "SAST",
        ex: "Static Application Security Testing",
        df: "Security testing that analyzes source code (without running it) to find vulnerabilities." },
      { ac: "ZAP",
        ex: "Zed Attack Proxy",
        df: "Open-source web app security testing tool." },
      ] },
    { name: "INDUSTRIAL & ENDPOINT",
      items: [
      { ac: "BIOS",
        ex: "Basic Input / Output",
        df: "Firmware that initializes hardware and starts the computer boot process." },
      { ac: "CPU",
        ex: "Central Processing Unit",
        df: "The main processor that executes instructions and performs calculations for the computer." },
      { ac: "ICS",
        ex: "Industrial Control Systems",
        df: "Networked systems used to monitor and control industrial processes often targeted in critical infrastructure attacks." },
      { ac: "OS",
        ex: "Operating System",
        df: "The core software that manages hardware and software resources and provides services for applications." },
      { ac: "OT",
        ex: "Operational Technology",
        df: "Systems used to control industrial equipment like SCADA often found in manufacturing or utilities." },
      { ac: "PLC",
        ex: "Programmable Logic Controller",
        df: "Industrial computer for automation." },
      { ac: "SCADA",
        ex: "Supervisory Control and Data Acquisition",
        df: "A control system used for industrial processes like power plants and water treatment." },
      { ac: "SMS",
        ex: "Short Message Service",
        df: "Text messaging service used in mobile devices sometimes leveraged in security notifications or MFA" },
      { ac: "USB",
        ex: "Universal Serial Bus",
        df: "A common interface used to connect peripherals to computers; can be a vector for malware if unmanaged." },
      ] },
    { name: "NETWORK SECURITY DEVICES",
      items: [
      { ac: "CASB",
        ex: "Cloud Access Security Broker",
        df: "A software tool or service that sits between users and cloud services to enforce security policies." },
      { ac: "CDN",
        ex: "Content Delivery Network",
        df: "Distributed system that delivers content quickly and reliably." },
      { ac: "NGFW",
        ex: "Next-generation Firewall",
        df: "An advanced firewall with features like deep packet inspection intrusion prevention and application awareness." },
      { ac: "SASE",
        ex: "Secure Access Service Edge",
        df: "A cloud-delivered architecture that combines networking and security into one service." },
      { ac: "SDN",
        ex: "Software-defined Networking",
        df: "An approach that separates the control plane from the data plane for flexible and programmable network management." },
      { ac: "SSID",
        ex: "Service Set Identifier",
        df: "The broadcast name that identifies a Wi-Fi network." },
      { ac: "SWG",
        ex: "Secure Web Gateway",
        df: "A security solution that filters web traffic to prevent access to malicious websites and enforce policy." },
      { ac: "VPN",
        ex: "Virtual Private Network",
        df: "A secure connection over the internet that encrypts data between a user and a private network." },
      { ac: "WAF",
        ex: "Web Application Firewall",
        df: "A security filter that monitors and blocks malicious traffic targeting web applications." },
      ] },
    { name: "CLOUD & VIRTUALIZATION",
      items: [
      { ac: "IaaS",
        ex: "Infrastructure as a Service",
        df: "Cloud-delivered virtualized computing resources." },
      { ac: "ISP",
        ex: "Internet Service Provider",
        df: "Company that provides access to the internet for individuals and organizations" },
      { ac: "MSP",
        ex: "Managed Service Provider",
        df: "A third-party company that remotely manages a customer's IT infrastructure and end-user systems." },
      { ac: "MSSP",
        ex: "Managed Security Service Provider",
        df: "A third-party vendor that provides outsourced monitoring and management of security systems." },
      { ac: "SaaS",
        ex: "Software as a Service",
        df: "A cloud computing model where applications are delivered over the internet and maintained by a provider." },
      { ac: "VM",
        ex: "Virtual Machine",
        df: "A software-emulated computer system that runs an OS and apps independently of the physical host system." },
      ] },
  ]
};
