/* =====================================================================
   FACE-OFF: CySA+  —  QUESTION POOL
   Exam: CompTIA CySA+ CS0-004 (V4, launched 23 June 2026)
   ---------------------------------------------------------------------
   12 categories x 10 clues = 120 board questions, plus 30 Lightning
   Final questions. Each category's clues run EASIEST first, HARDEST
   last — that ordering becomes the 100 → 500 rows on the board.

   A NOTE ON THE `obj` TAGS
   CompTIA has not published CS0-004's granular objective numbering
   (1.1, 1.2, …) publicly yet. Rather than invent numbers, clues are
   tagged by DOMAIN and TOPIC AREA, which are confirmed. If you have the
   official CS0-004 objectives PDF, you can drop exact numbers into the
   `obj` field and nothing else needs to change.

   Domain weights (CS0-004):
     D1 Security Operations 34% · D2 Vulnerability Management 26%
     D3 Incident Response & Management 24% · D4 Reporting & Comms 16%

   CySA+ is an ANALYST exam — these questions lean on interpreting output
   and making prioritization calls, not reciting definitions.
   ===================================================================== */

window.FACEOFF_QUESTIONS = {
  exam: "CompTIA CySA+ (CS0-004)",

  categories: [

  /* ============ 1 ============ */
  { name: "ARCHITECTURE & FOUNDATIONS", obj: "D1 · Architecture", clues: [
    { q: "Name the centralized team responsible for detecting, analyzing, and responding to incidents in real time.",
      a: "The SOC — Security Operations Center", alt: ["SOC"], obj: "D1 · Architecture" },
    { q: "Dividing a network into isolated zones so a compromise can't spread laterally is called this.",
      a: "Network segmentation", obj: "D1 · Architecture" },
    { q: "Name the logging concept of collecting logs from many sources into one searchable place.",
      a: "Log aggregation (centralized logging)", alt: ["Aggregation"], obj: "D1 · Architecture" },
    { q: "This model assumes no implicit trust from network location and verifies every request.",
      a: "Zero Trust", obj: "D1 · Architecture" },
    { q: "Explain why an accurate asset inventory is the foundation of detection, not just an IT chore.",
      a: "You cannot monitor, patch, or alert on what you don't know exists — unknown assets are blind spots that never generate telemetry",
      alt: ["Can't detect what you don't know about"], obj: "D1 · Architecture" },
    { q: "Name the two Zero Trust planes and what each does.",
      a: "The control plane makes the policy decision; the data plane enforces it at the policy enforcement point",
      alt: ["Control decides, data enforces"], obj: "D1 · Architecture" },
    { q: "Explain what makes cloud telemetry different from on-premises telemetry for an analyst.",
      a: "You lose packet-level visibility and rely on provider APIs and flow/audit logs, the shared responsibility model limits what you can see, and assets appear and vanish in minutes",
      alt: ["API-based, ephemeral, shared responsibility"], obj: "D1 · Architecture" },
    { q: "Name the identity concept where a user's access is evaluated on context — device, location, time — at the moment of the request.",
      a: "Attribute-based / conditional access", alt: ["ABAC", "Conditional access"], obj: "D1 · Architecture" },
    { q: "Explain why NTP accuracy is a prerequisite for incident analysis.",
      a: "Correlating events across systems depends on a shared timeline — skewed clocks make it impossible to establish sequence, and can invalidate evidence",
      alt: ["Timeline correlation and evidence integrity"], obj: "D1 · Architecture" },
    { q: "Your organization runs on-prem, two clouds, and SaaS. Name three things this hybrid reality does to your detection coverage.",
      a: "Log formats and retention differ per platform, identity is federated across boundaries so lateral movement crosses them, and no single tool sees everything — leaving seams between environments",
      alt: ["Different formats, federated identity, coverage seams"], obj: "D1 · Architecture" }
  ]},

  /* ============ 2 ============ */
  { name: "INDICATORS OF MALICIOUS ACTIVITY", obj: "D1 · Indicators", clues: [
    { q: "A single account logs in from two countries minutes apart. Name this indicator.",
      a: "Impossible travel", obj: "D1 · Indicators" },
    { q: "A workstation suddenly starts communicating with a host it has never contacted, on a regular interval.",
      a: "Beaconing — likely command and control", alt: ["Beaconing", "C2"], obj: "D1 · Indicators" },
    { q: "Large volumes of data leaving the network at 3 a.m. from a workstation is an indicator of this.",
      a: "Data exfiltration", obj: "D1 · Indicators" },
    { q: "Name the host indicator where a process runs from a temp or user-writable directory instead of Program Files.",
      a: "Suspicious process location / unusual execution path", alt: ["Odd process path"], obj: "D1 · Indicators" },
    { q: "Explain what living-off-the-land means and name two binaries attackers abuse.",
      a: "Using legitimate built-in tools so nothing malicious is dropped — PowerShell, certutil, wmic, rundll32, psexec (any two)",
      alt: ["LOLBins; PowerShell, certutil"], obj: "D1 · Indicators" },
    { q: "A domain resolves to a different IP every few minutes across many hosts. Name the technique.",
      a: "Fast flux DNS", obj: "D1 · Indicators" },
    { q: "You see DNS queries to long random-looking subdomains of one domain, thousands per hour. Explain what's happening.",
      a: "DNS tunneling — data is being encoded into query names to exfiltrate or carry C2 past egress filtering",
      alt: ["DNS tunneling / exfil over DNS"], obj: "D1 · Indicators" },
    { q: "A service account that has only ever run at 2 a.m. suddenly authenticates interactively at midday. Explain what you'd suspect and why it matters.",
      a: "Credential compromise — service accounts shouldn't log in interactively, and they usually hold elevated standing privileges",
      alt: ["Compromised service account"], obj: "D1 · Indicators" },
    { q: "Explain the difference between an IoC and a TTP, and which is more durable for defense.",
      a: "An IoC is a specific artifact — a hash, an IP — that an attacker can change trivially. A TTP describes their behavior, which is far more expensive to change, so TTP-based detection lasts longer",
      alt: ["IoC = artifact, TTP = behavior; TTP durable"], obj: "D1 · Indicators" },
    { q: "One host shows: new scheduled task, outbound TLS to a new ASN, and a service binary replaced. Explain the stage and your immediate action.",
      a: "Persistence plus C2 establishment — post-exploitation, pre-exfiltration. Isolate the host from the network while preserving memory, then hunt for the same indicators elsewhere",
      alt: ["Persistence + C2; isolate and hunt laterally"], obj: "D1 · Indicators" }
  ]},

  /* ============ 3 ============ */
  { name: "ANALYSIS TOOLS & FORMATS", obj: "D1 · Tools", clues: [
    { q: "This tool captures and lets you inspect network packets in detail.",
      a: "Wireshark", alt: ["Packet analyzer"], obj: "D1 · Tools" },
    { q: "This system aggregates and correlates logs and generates alerts.",
      a: "SIEM", obj: "D1 · Tools" },
    { q: "This pattern-matching language is the standard for writing malware identification rules.",
      a: "YARA", obj: "D1 · Tools" },
    { q: "Name the machine-readable formats for sharing threat intelligence, and what each does.",
      a: "STIX describes the intelligence; TAXII is the protocol that transports it",
      alt: ["STIX and TAXII"], obj: "D1 · Tools" },
    { q: "Name the open format for writing portable SIEM detection rules that convert to any vendor's query language.",
      a: "Sigma", obj: "D1 · Tools" },
    { q: "Name the tool that gives you flow-level metadata about who talked to whom, without full packet capture.",
      a: "NetFlow / sFlow / IPFIX", alt: ["NetFlow"], obj: "D1 · Tools" },
    { q: "Explain when you'd use full packet capture instead of flow data, and the cost of doing so.",
      a: "When you need actual content — payloads, exfiltrated data, exploit detail. The cost is enormous storage and, with TLS everywhere, much of it is encrypted anyway",
      alt: ["For content; costs storage"], obj: "D1 · Tools" },
    { q: "Explain what a JA3 or JA4 fingerprint identifies, and why it survives encryption.",
      a: "It fingerprints the TLS client handshake — the parameters and their order — so you can identify the client software even though the payload is encrypted",
      alt: ["TLS handshake fingerprint"], obj: "D1 · Tools" },
    { q: "A sandbox reports a sample as benign but you still suspect it. Name three reasons a sandbox produces a false negative.",
      a: "The malware detects the sandbox and stays dormant, it's time-delayed, it needs a C2 server that's now offline, or it requires specific user interaction or a target environment (any three)",
      alt: ["Sandbox evasion, time delay, dead C2, needs interaction"], obj: "D1 · Tools" },
    { q: "Explain the analytical difference between correlation and aggregation in a SIEM.",
      a: "Aggregation gathers and normalizes events into one place; correlation applies logic ACROSS those events to infer something no single event shows — like a failed-login burst followed by one success and a privilege change",
      alt: ["Aggregation collects, correlation reasons across events"], obj: "D1 · Tools" }
  ]},

  /* ============ 4 ============ */
  { name: "THREAT INTEL, HUNTING & AI", obj: "D1 · Intel & Automation", clues: [
    { q: "Name the practice of proactively searching for threats that evaded existing detections.",
      a: "Threat hunting", obj: "D1 · Hunting" },
    { q: "Name the intelligence source type gathered from public sources like blogs, CERT bulletins, and the dark web.",
      a: "OSINT — open source intelligence", alt: ["Open source"], obj: "D1 · Intel" },
    { q: "Name the three confidence attributes used to judge a piece of threat intelligence.",
      a: "Timeliness, relevancy, and accuracy", obj: "D1 · Intel" },
    { q: "A threat hunt starts with one of these — a testable statement about what an attacker might be doing.",
      a: "A hypothesis", obj: "D1 · Hunting" },
    { q: "Name the platform that automates response playbooks on top of a SIEM's detections.",
      a: "SOAR", alt: ["Security Orchestration, Automation and Response"], obj: "D1 · Automation" },
    { q: "Explain the difference between strategic, operational, and tactical threat intelligence by audience.",
      a: "Strategic is long-horizon risk for executives; operational describes campaigns and actor behavior for SOC leadership; tactical is IoCs and TTPs analysts act on today",
      alt: ["Exec, campaign, analyst-level"], obj: "D1 · Intel" },
    { q: "Explain why a threat hunt that finds nothing is still a success.",
      a: "It validates coverage and reduces uncertainty — and the hypothesis, queries, and any visibility gaps it exposed become new detections",
      alt: ["Validates coverage, produces detections"], obj: "D1 · Hunting" },
    { q: "Name three legitimate uses of AI in security operations, and the single biggest risk of relying on it.",
      a: "Alert triage and deduplication, anomaly and behavioral detection, log summarization, and enrichment. The risk is unexplainable output — an analyst who can't verify why it flagged something can't defend the decision, and models can be poisoned or evaded",
      alt: ["Triage, anomaly detection, summarization; risk is explainability"], obj: "D1 · AI" },
    { q: "Explain what makes a good SOC efficiency metric, using MTTD and MTTR as the example.",
      a: "Mean time to detect and mean time to respond measure the outcome that matters — how long an attacker had. Counting alerts closed measures activity, not effectiveness, and rewards closing tickets fast",
      alt: ["MTTD/MTTR measure outcomes, not activity"], obj: "D1 · Process" },
    { q: "Your intel feed delivers 40,000 indicators a day and your SIEM chokes. Explain how you'd make the feed useful.",
      a: "Filter for relevancy to your actual environment and tech stack, weight by confidence and recency, expire stale indicators automatically, and pivot from atomic IoCs toward behavioral TTP detections",
      alt: ["Filter by relevance/confidence, age out, move to TTPs"], obj: "D1 · Intel" }
  ]},

  /* ============ 5 ============ */
  { name: "SCANNING APPROACHES", obj: "D2 · Scanning", clues: [
    { q: "Explain the difference between an active and a passive scan.",
      a: "Active scanning sends probes to the target; passive observes existing traffic without touching it",
      alt: ["Active probes, passive observes"], obj: "D2 · Scanning" },
    { q: "Explain the difference between a credentialed and a non-credentialed scan.",
      a: "A credentialed scan logs in and reads actual patch and config state; a non-credentialed scan only sees what's exposed externally",
      alt: ["Logged in vs outside view"], obj: "D2 · Scanning" },
    { q: "Which gives more accurate results with fewer false positives — credentialed or non-credentialed?",
      a: "Credentialed", obj: "D2 · Scanning" },
    { q: "Name the scan type that uses software installed on the host itself rather than reaching in over the network.",
      a: "Agent-based scanning", obj: "D2 · Scanning" },
    { q: "Explain why you'd choose agent-based scanning for a remote workforce.",
      a: "Laptops are rarely on the corporate network when a scan window runs — an agent reports whenever the device is online, wherever it is",
      alt: ["Devices aren't on the network"], obj: "D2 · Scanning" },
    { q: "Name two real risks of running an aggressive active scan against production.",
      a: "Crashing fragile services or legacy/OT devices, saturating bandwidth, triggering account lockouts, and flooding the SOC with alerts (any two)",
      alt: ["Service crashes, lockouts, bandwidth, alert noise"], obj: "D2 · Scanning" },
    { q: "Explain what SCAP provides to a vulnerability program.",
      a: "A standardized set of specifications so tools express vulnerabilities, configurations, and scoring the same way — making results comparable and automatable across vendors",
      alt: ["Standard format for automated assessment"], obj: "D2 · Scanning" },
    { q: "Explain the difference between vulnerability scanning and attack surface management.",
      a: "Scanning assesses assets you already know about; ASM continuously discovers what you're exposing that you didn't know about — shadow IT, forgotten cloud assets, expired domains",
      alt: ["Known assets vs discovering unknown exposure"], obj: "D2 · Scanning" },
    { q: "Explain why scanning an OT or ICS environment demands a different approach than IT.",
      a: "Those devices often crash on ordinary probes and cannot be taken offline — use passive monitoring and vendor-approved methods, and test in a lab first. Availability and safety outrank patching",
      alt: ["Fragile, availability first, use passive"], obj: "D2 · Scanning" },
    { q: "Explain how container and image scanning differs from scanning a traditional server.",
      a: "You scan the image in the registry before deployment rather than the running host, the base image inherits its parents' vulnerabilities, and containers are immutable — you rebuild and redeploy instead of patching in place",
      alt: ["Scan images pre-deploy; rebuild not patch"], obj: "D2 · Scanning" }
  ]},

  /* ============ 6 ============ */
  { name: "ANALYSIS & PRIORITIZATION", obj: "D2 · Prioritization", clues: [
    { q: "This 0–10 score rates a vulnerability's technical severity.",
      a: "CVSS", obj: "D2 · Prioritization" },
    { q: "This catalog gives every publicly known vulnerability a unique identifier.",
      a: "CVE", obj: "D2 · Prioritization" },
    { q: "Name the scan result where a reported vulnerability isn't actually there.",
      a: "A false positive", obj: "D2 · Prioritization" },
    { q: "Name the scan result that is the most dangerous for an analyst, and explain why.",
      a: "A false negative — a real vulnerability nobody knows about, so it never gets fixed",
      alt: ["False negative"], obj: "D2 · Prioritization" },
    { q: "Name the three CVSS metric groups.",
      a: "Base, Temporal (Threat), and Environmental", obj: "D2 · Prioritization" },
    { q: "Name the catalog of vulnerabilities that are confirmed to be actively exploited in the wild.",
      a: "CISA's KEV — Known Exploited Vulnerabilities catalog", alt: ["KEV catalog"], obj: "D2 · Prioritization" },
    { q: "Explain what EPSS adds that CVSS alone doesn't give you.",
      a: "EPSS estimates the probability the vulnerability will actually be exploited in the near term — CVSS only describes how bad it would be if it were",
      alt: ["Likelihood of exploitation vs severity"], obj: "D2 · Prioritization" },
    { q: "You have a CVSS 9.8 on an isolated lab box and a 6.5 on an internet-facing payment server. Explain which you fix first and why.",
      a: "The 6.5 — prioritization is severity in CONTEXT: exposure, asset criticality, data sensitivity, and whether an exploit exists. The isolated box has compensating isolation",
      alt: ["The 6.5; context beats raw score"], obj: "D2 · Prioritization" },
    { q: "Name three pieces of context that should override a raw CVSS score when prioritizing.",
      a: "Whether it's internet-facing, asset criticality and data classification, whether a weaponized exploit exists (KEV/EPSS), and existing compensating controls (any three)",
      alt: ["Exposure, asset value, exploit availability, controls"], obj: "D2 · Prioritization" },
    { q: "Explain why a vulnerability count is a poor executive metric, and give one better.",
      a: "Raw counts don't reflect risk and go up whenever coverage improves — better: mean time to remediate critical exposed findings, or percentage of KEV items closed within SLA",
      alt: ["Counts ignore risk; use MTTR on critical/KEV"], obj: "D2 · Prioritization" }
  ]},

  /* ============ 7 ============ */
  { name: "TREATMENT & VALIDATION", obj: "D2 · Response", clues: [
    { q: "Name the four valid ways to treat an identified risk.",
      a: "Accept, Avoid, Transfer, Mitigate", obj: "D2 · Response" },
    { q: "Applying a patch is which risk treatment?",
      a: "Mitigation", obj: "D2 · Response" },
    { q: "Name the formal record that documents an accepted, unremediated vulnerability.",
      a: "A risk exception / exemption, signed off by the risk owner",
      alt: ["Exception or exemption"], obj: "D2 · Response" },
    { q: "Name the step that must follow every remediation.",
      a: "Validation — rescan or retest to confirm the fix actually worked",
      alt: ["Rescan / validate"], obj: "D2 · Response" },
    { q: "Name the control you deploy in front of an app when you cannot patch the app itself.",
      a: "A WAF with virtual patching rules", alt: ["WAF / virtual patching"], obj: "D2 · Response" },
    { q: "Name three reasons a legacy or proprietary system can't simply be patched.",
      a: "The vendor no longer issues patches, the patch breaks a certified or dependent application, there's no maintenance window, or the warranty/certification forbids modification (any three)",
      alt: ["EOL vendor, breaks app, no window, certification"], obj: "D2 · Response" },
    { q: "Explain why a change control process matters for remediation, from a security perspective.",
      a: "Uncoordinated fixes cause outages that get security blamed and future patching blocked — and an undocumented change hides the cause of the next incident",
      alt: ["Prevents outages and preserves the baseline"], obj: "D2 · Response" },
    { q: "Explain the difference between remediation and mitigation in vulnerability management.",
      a: "Remediation eliminates the vulnerability — patch, upgrade, remove. Mitigation reduces exploitability while it remains — segmentation, WAF rules, disabling the feature",
      alt: ["Remove vs reduce"], obj: "D2 · Response" },
    { q: "Name what an SLO does for a vulnerability program, and give a realistic example.",
      a: "It sets a measurable, agreed deadline by severity — for example, critical internet-facing findings remediated in 7 days, high in 30",
      alt: ["Time-bound remediation targets by severity"], obj: "D2 · Response" },
    { q: "A remediation rescan comes back clean but the asset is still being exploited. Name three explanations.",
      a: "The scan didn't actually cover that host or port, the fix needs a reboot that hasn't happened, the attacker already has persistence that patching doesn't remove, or there's a second unpatched path in (any three)",
      alt: ["Coverage gap, no reboot, existing persistence, another path"], obj: "D2 · Response" }
  ]},

  /* ============ 8 ============ */
  { name: "ATTACK FRAMEWORKS", obj: "D3 · Frameworks", clues: [
    { q: "Name the framework that catalogs adversary tactics and techniques in a matrix.",
      a: "MITRE ATT&CK", obj: "D3 · Frameworks" },
    { q: "Name the seven-stage model that runs from Reconnaissance to Actions on Objectives.",
      a: "The Cyber Kill Chain", alt: ["Lockheed Martin Kill Chain"], obj: "D3 · Frameworks" },
    { q: "Name the four vertices of the Diamond Model.",
      a: "Adversary, Capability, Infrastructure, and Victim", obj: "D3 · Frameworks" },
    { q: "In ATT&CK, explain the difference between a tactic and a technique.",
      a: "A tactic is the adversary's goal — the WHY, like Persistence. A technique is HOW they achieve it, like a scheduled task",
      alt: ["Tactic = goal, technique = method"], obj: "D3 · Frameworks" },
    { q: "Name the first and last stages of the Cyber Kill Chain.",
      a: "Reconnaissance first, Actions on Objectives last", obj: "D3 · Frameworks" },
    { q: "Explain the main criticism of the Cyber Kill Chain compared with ATT&CK.",
      a: "It's linear and perimeter-focused, so it models an intrusion poorly once the attacker is inside or when they're an insider — ATT&CK maps behavior at any stage without assuming order",
      alt: ["Too linear and perimeter-centric"], obj: "D3 · Frameworks" },
    { q: "Explain how you'd use ATT&CK to find gaps in your detection coverage.",
      a: "Map every existing detection to the techniques it covers, overlay the techniques your likely threat actors actually use, and the uncovered high-relevance techniques become your detection backlog",
      alt: ["Coverage mapping / heat map against actor TTPs"], obj: "D3 · Frameworks" },
    { q: "Explain what the Diamond Model gives an analyst that the Kill Chain does not.",
      a: "It shows the relationships between the four features, so pivoting on one — an IP, a hash, a victim profile — surfaces the others and supports attribution and clustering of related activity",
      alt: ["Pivoting and relationships for attribution"], obj: "D3 · Frameworks" },
    { q: "Name the framework used to describe an adversary's activity from the defender's detection maturity perspective, and what climbing it costs the attacker.",
      a: "The Pyramid of Pain — the higher you detect (TTPs rather than hashes or IPs), the more expensive it is for the attacker to change",
      alt: ["Pyramid of Pain"], obj: "D3 · Frameworks" },
    { q: "You must brief an executive on an intrusion using ONE framework. Explain which you'd pick and why.",
      a: "The Kill Chain — its linear narrative maps to a story an executive follows and shows where the attack was stopped or should have been. ATT&CK is the right tool for the analyst detail underneath",
      alt: ["Kill Chain for narrative, ATT&CK for detail"], obj: "D3 · Frameworks" }
  ]},

  /* ============ 9 ============ */
  { name: "INCIDENT RESPONSE", obj: "D3 · IR Lifecycle", clues: [
    { q: "Name the first phase of the incident response life cycle.",
      a: "Preparation", obj: "D3 · IR Lifecycle" },
    { q: "Name all the incident response phases in order.",
      a: "Preparation, Detection and Analysis, Containment, Eradication, Recovery, and Post-incident (Lessons Learned)",
      alt: ["Prep, detect/analyze, contain, eradicate, recover, lessons learned"], obj: "D3 · IR Lifecycle" },
    { q: "Isolating an infected host from the network is which phase?",
      a: "Containment", obj: "D3 · IR Lifecycle" },
    { q: "Removing the malware and closing the exploited vulnerability is which phase?",
      a: "Eradication", obj: "D3 · IR Lifecycle" },
    { q: "Name the document that defines who does what during an incident, before one happens.",
      a: "The incident response plan (with playbooks and a call/escalation tree)",
      alt: ["IR plan"], obj: "D3 · IR Lifecycle" },
    { q: "Explain the difference between containment and eradication.",
      a: "Containment stops the spread and limits damage right now; eradication removes the root cause entirely so it can't recur",
      alt: ["Stop spread vs remove cause"], obj: "D3 · IR Lifecycle" },
    { q: "Explain the trade-off between isolating a compromised host and powering it off.",
      a: "Powering off destroys volatile evidence — memory, keys, running processes, live connections. Isolating preserves it while cutting the attacker off, which is usually preferred",
      alt: ["Power-off loses volatile evidence; isolate instead"], obj: "D3 · IR Lifecycle" },
    { q: "Name three criteria used to classify an incident's severity.",
      a: "Data sensitivity and volume, business/system criticality, scope and number of systems affected, downtime, recoverability, and regulatory or reputational exposure (any three)",
      alt: ["Data, criticality, scope, downtime, regulatory"], obj: "D3 · IR Lifecycle" },
    { q: "Explain the purpose of the post-incident review and the one rule that makes it work.",
      a: "To turn the incident into improved detections, controls, and playbooks — it only works if it's blameless, or people stop reporting and stop being candid",
      alt: ["Improve; must be blameless"], obj: "D3 · IR Lifecycle" },
    { q: "Ransomware is spreading across file shares right now. Give your first three actions in order, and say what you must NOT do.",
      a: "Isolate affected hosts and disable the propagation path (accounts, shares, SMB), preserve volatile evidence and identify the strain and entry point, then verify backups are intact and offline. Do NOT reboot or wipe systems before capturing evidence, and don't restore into a network the attacker still holds",
      alt: ["Isolate, preserve/identify, verify backups; don't wipe or restore early"], obj: "D3 · IR Lifecycle" }
  ]},

  /* ============ 10 ============ */
  { name: "FORENSICS & EVIDENCE", obj: "D3 · Forensics", clues: [
    { q: "This documented trail proves who handled evidence and when.",
      a: "Chain of custody", obj: "D3 · Forensics" },
    { q: "Name the order of volatility, most volatile first.",
      a: "CPU registers and cache, RAM, network state and running processes, disk, then logs and backups, then archival media",
      alt: ["Registers, RAM, network, disk, backups"], obj: "D3 · Forensics" },
    { q: "Name the obligation triggered when litigation becomes reasonably anticipated.",
      a: "Legal hold — suspend deletion and rotation of potentially relevant data",
      alt: ["Legal hold"], obj: "D3 · Forensics" },
    { q: "Name what you compute before and after imaging a drive, and why.",
      a: "A cryptographic hash of the image — matching hashes prove the copy is identical and unaltered",
      alt: ["Hash for integrity"], obj: "D3 · Forensics" },
    { q: "Name the device that lets you read a drive without any possibility of altering it.",
      a: "A write blocker", obj: "D3 · Forensics" },
    { q: "Explain why you analyze a forensic image rather than the original drive.",
      a: "Any interaction with the original changes it and can render the evidence inadmissible — the verified image preserves the original untouched",
      alt: ["Preserve the original / admissibility"], obj: "D3 · Forensics" },
    { q: "Explain what a memory capture gives you that a disk image cannot.",
      a: "Encryption keys, injected and fileless malware, decrypted data, active network connections, and running process state — none of which touch the disk",
      alt: ["Keys, fileless malware, live state"], obj: "D3 · Forensics" },
    { q: "Explain the challenge of forensics in a cloud or containerized environment.",
      a: "You often can't image the underlying hardware, containers vanish on restart taking evidence with them, and you depend on provider APIs, logging that may not be enabled, and jurisdictional limits",
      alt: ["No hardware access, ephemeral, provider-dependent"], obj: "D3 · Forensics" },
    { q: "Name three types of artifact you'd examine on a Windows host to establish what an attacker executed.",
      a: "Prefetch, Shimcache/Amcache, the registry (Run keys, services), Windows event logs, ShellBags, jump lists, and PowerShell operational logs (any three)",
      alt: ["Prefetch, Amcache, registry, event logs"], obj: "D3 · Forensics" },
    { q: "An analyst logs into a compromised server with domain admin credentials to investigate. Explain everything wrong with that.",
      a: "It exposes those credentials to an attacker who still controls the host, contaminates the evidence and timeline with the analyst's own activity, and can trigger the attacker to destroy evidence. Investigate remotely from a trusted platform with a dedicated, limited account",
      alt: ["Exposes creds, contaminates evidence, tips off attacker"], obj: "D3 · Forensics" }
  ]},

  /* ============ 11 ============ */
  { name: "VULNERABILITY REPORTING", obj: "D4 · Vuln Reporting", clues: [
    { q: "Name the two broad kinds of vulnerability report.",
      a: "A summary of existing vulnerabilities, and a detailed report outlining specific mitigations",
      alt: ["Summary and detailed/mitigation"], obj: "D4 · Vuln Reporting" },
    { q: "Name the metric that shows whether your vulnerability program is improving over time.",
      a: "Trends — vulnerability counts and remediation times tracked across periods",
      alt: ["Trend analysis"], obj: "D4 · Vuln Reporting" },
    { q: "Name the prioritized list used to focus effort on the most significant risks.",
      a: "A Top 10 (critical/most-exploitable list)", obj: "D4 · Vuln Reporting" },
    { q: "Name the stakeholder group that owns fixing most findings, and the friction that creates.",
      a: "System and application owners / IT operations — security finds the issue but doesn't control the remediation window or the risk acceptance",
      alt: ["System owners; security doesn't control the fix"], obj: "D4 · Vuln Reporting" },
    { q: "Explain how you'd report the same finding differently to an executive versus a system administrator.",
      a: "The executive gets business risk, exposure, and cost or time to fix; the administrator gets the affected hosts, the exact CVE, and the specific remediation steps",
      alt: ["Business risk vs technical steps"], obj: "D4 · Vuln Reporting" },
    { q: "Explain what an inhibitor to remediation is and name three common ones.",
      a: "Something preventing a fix from being applied — MOUs or SLAs, organizational governance, business process interruption, degrading functionality, or a legacy/proprietary system (any three)",
      alt: ["MOU/SLA, governance, business interruption, legacy"], obj: "D4 · Vuln Reporting" },
    { q: "Explain why compliance reporting and risk reporting are not the same thing.",
      a: "Compliance proves you met a required standard at a point in time; risk reporting says how exposed you actually are now. You can be fully compliant and badly exposed",
      alt: ["Compliant ≠ secure"], obj: "D4 · Vuln Reporting" },
    { q: "Your report says the same 200 criticals every month. Explain what that tells you and what to change.",
      a: "The reporting isn't driving action — the findings likely have no owner, no SLA, or no accepted-risk record. Assign owners, set severity-based SLOs, escalate breaches, and formally document what's being accepted",
      alt: ["No ownership or SLA; assign owners and escalate"], obj: "D4 · Vuln Reporting" },
    { q: "Explain the risk of reporting only raw vulnerability counts to leadership.",
      a: "Counts move with scanner coverage rather than risk — expanding scanning makes the numbers look worse while security improves, which erodes trust and discourages better coverage",
      alt: ["Counts track coverage, not risk"], obj: "D4 · Vuln Reporting" },
    { q: "Name three things an effective vulnerability report must contain beyond the list of findings.",
      a: "Affected assets and business context, prioritization rationale, specific recommended actions with owners, remediation timelines against SLOs, and accepted-risk exceptions (any three)",
      alt: ["Context, prioritization rationale, actions/owners, timelines"], obj: "D4 · Vuln Reporting" }
  ]},

  /* ============ 12 ============ */
  { name: "INCIDENT COMMUNICATION", obj: "D4 · IR Reporting", clues: [
    { q: "Name the document that says who gets told what, and when, during an incident.",
      a: "The communication plan", obj: "D4 · IR Reporting" },
    { q: "Name the analysis that identifies the underlying reason an incident happened.",
      a: "Root cause analysis", obj: "D4 · IR Reporting" },
    { q: "Name the meeting held after an incident to capture what to improve.",
      a: "The lessons learned / post-incident review", obj: "D4 · IR Reporting" },
    { q: "Name two external parties who may legally have to be notified after a breach.",
      a: "Regulators, affected individuals, law enforcement, customers or partners under contract, and cyber insurers (any two)",
      alt: ["Regulators and affected individuals"], obj: "D4 · IR Reporting" },
    { q: "Explain why incident communications should go through one designated channel and spokesperson.",
      a: "Conflicting or premature statements create legal exposure and destroy credibility — and early technical detail is often wrong",
      alt: ["Avoid conflicting/premature statements"], obj: "D4 · IR Reporting" },
    { q: "Explain what a stakeholder identification exercise prevents during an incident.",
      a: "Scrambling mid-incident to work out who must be told — legal, PR, execs, regulators, customers — which costs time and blows notification deadlines",
      alt: ["Prevents scrambling and missed deadlines"], obj: "D4 · IR Reporting" },
    { q: "Explain why the technical timeline in an incident report matters legally, not just operationally.",
      a: "Regulatory notification clocks start at discovery, and a defensible, timestamped record of what was known when is what proves you met the deadline and acted reasonably",
      alt: ["Proves notification timelines were met"], obj: "D4 · IR Reporting" },
    { q: "Explain the risk of stating a root cause publicly before the investigation is complete.",
      a: "Early theories are frequently wrong — retracting one destroys credibility, may create liability, and can mislead your own responders and other victims",
      alt: ["Early theories are usually wrong"], obj: "D4 · IR Reporting" },
    { q: "Name the metrics an incident report should carry so the program can be measured.",
      a: "Mean time to detect, to respond, and to recover; dwell time; scope and impact; and whether existing controls or detections worked",
      alt: ["MTTD, MTTR, dwell time, scope, control efficacy"], obj: "D4 · IR Reporting" },
    { q: "A breach is confirmed at 4 p.m. Friday. Explain your first three communication actions and the mistake to avoid.",
      a: "Notify the incident commander and legal counsel, activate the designated channel and start the timestamped log, and brief executives with what is CONFIRMED versus suspected. Avoid mass-notifying staff or customers before legal and the facts are settled — and never discuss it on potentially compromised systems",
      alt: ["Legal + IC first, single channel, confirmed facts only"], obj: "D4 · IR Reporting" }
  ]}

  ],

  /* =====================================================================
     LIGHTNING FINAL — head to head between the last two teams.
     ===================================================================== */
  lightning: [
    { q: "What does SOC stand for?", a: "Security Operations Center", obj: "D1" },
    { q: "What does SIEM stand for?", a: "Security Information and Event Management", obj: "D1" },
    { q: "What does SOAR add to a SIEM?", a: "Orchestration and automated response", obj: "D1" },
    { q: "Which framework is the tactics-and-techniques matrix?", a: "MITRE ATT&CK", obj: "D3" },
    { q: "How many stages in the Cyber Kill Chain?", a: "Seven", obj: "D3" },
    { q: "Name the four vertices of the Diamond Model.", a: "Adversary, Capability, Infrastructure, Victim", obj: "D3" },
    { q: "What's the first phase of incident response?", a: "Preparation", obj: "D3" },
    { q: "Isolating a host is which IR phase?", a: "Containment", obj: "D3" },
    { q: "What proves who handled evidence and when?", a: "Chain of custody", obj: "D3" },
    { q: "What's the most volatile evidence source?", a: "CPU registers and cache", alt: ["Registers/cache"], obj: "D3" },
    { q: "What scores a vulnerability 0 to 10?", a: "CVSS", obj: "D2" },
    { q: "What estimates the likelihood a CVE gets exploited?", a: "EPSS", obj: "D2" },
    { q: "What's CISA's actively-exploited catalog called?", a: "The KEV catalog", obj: "D2" },
    { q: "Credentialed or non-credentialed — which is more accurate?", a: "Credentialed", obj: "D2" },
    { q: "What's a reported vulnerability that isn't real?", a: "A false positive", obj: "D2" },
    { q: "Which scan result is most dangerous to an analyst?", a: "A false negative", obj: "D2" },
    { q: "Name the four risk treatments.", a: "Accept, Avoid, Transfer, Mitigate", obj: "D2" },
    { q: "What must follow every remediation?", a: "Validation — a rescan", obj: "D2" },
    { q: "What are the two threat intel sharing formats?", a: "STIX and TAXII", obj: "D1" },
    { q: "What language writes malware identification rules?", a: "YARA", obj: "D1" },
    { q: "What open format writes portable SIEM detection rules?", a: "Sigma", obj: "D1" },
    { q: "What does a threat hunt start with?", a: "A hypothesis", obj: "D1" },
    { q: "What does OSINT stand for?", a: "Open Source Intelligence", obj: "D1" },
    { q: "Regular outbound traffic to one host at fixed intervals is called what?", a: "Beaconing", obj: "D1" },
    { q: "One account logging in from two countries at once is called what?", a: "Impossible travel", obj: "D1" },
    { q: "What does MTTD measure?", a: "Mean time to detect", obj: "D1" },
    { q: "What device lets you read a drive without altering it?", a: "A write blocker", obj: "D3" },
    { q: "What suspends deletion when litigation is anticipated?", a: "A legal hold", obj: "D3" },
    { q: "IoC or TTP — which is harder for an attacker to change?", a: "TTP", obj: "D1" },
    { q: "What makes a lessons-learned review actually work?", a: "It has to be blameless", obj: "D4" }
  ]
};
